Use closure-compiler commit 5ff0611 for externs
Recent updates to the angular-1.4 externs cause the following compilation error:

```
ERR! compile .build/externs/angular-1.4.js:2234: ERROR - Bad type annotation.  missing closing )
ERR! compile * @typedef {function(Function, number=, boolean=, ...=):!angular.$q.Promise}
```

Fixing the problem requires using a more recent version of Closure Compiler. There's https://github.com/openlayers/closure-util/pull/67, but it's not merged yet. In the mean time this commit uses a specific commit when downloading the closure-compiler externs.

Fixes #840.